version: "3.9"
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: password123
            POSTGRES_USER: user123
            POSTGRES_DB: db123
    app:
        container_name: server
        image: server
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - 5000:5000
